global:
  resolve_timeout: 5m

route:
  receiver: "telegram"
  group_by: ["alertname", "mountpoint"]
  routes:
    - matchers:
      - severity="critical"
      group_wait: 10s
      group_interval: 5m
      repeat_interval: 2h

    - matchers:
      - severity="warning"
      group_wait: 30s
      group_interval: 10m
      repeat_interval: 4h



receivers:
  - name: "telegram"
    telegram_configs:
      - bot_token_file: /etc/alertmanager/telegram_token
        chat_id: 451454036
        http_config:
          proxy_url: socks5://tunnel:1080